package com.pixandroid.musicpad.utils;

/**
 * BuildConfig stub for compilation
 * The actual BuildConfig will be generated by the build system
 */
public class BuildConfig {
    public static final boolean DEBUG = true;
    public static final String APPLICATION_ID = "com.pixandroid.musicpad";
    public static final String BUILD_TYPE = "debug";
    public static final int VERSION_CODE = 1;
    public static final String VERSION_NAME = "1.0.0";
}
